{
  flake.modules.home."agents/reasonix" =
    {
      pkgs,
      config,
      lib,
      ...
    }:
    let
      inherit (config.age.secrets) deepseek-api-key;

      # XDG-compatible home: Reasonix v1.8.1+ keeps config, credentials, and
      # state under $REASONIX_HOME (default ~/.reasonix); pointing it at
      # ~/.config/reasonix keeps everything in the XDG tree.
      reasonixHome = "${config.xdg.configHome}/reasonix";

      reasonixWrapped = pkgs.writeShellScriptBin "reasonix" ''
        # Provider keys come from <home>/.env (reasonix's only credential
        # source; process env is not read). Keep them out of the shell env so
        # reasonix can scrub them from model-controlled child processes.
        export REASONIX_HOME="${reasonixHome}"
        exec ${lib.getExe pkgs.llm-agents.reasonix} "$@"
      '';

      # v1.19.x schema (config_version = 3), following the default generated by
      # `reasonix setup` with the deepseek providers declared explicitly.
      # [codegraph] is gone from the current schema and no longer configured.
      # Read-only: runtime settings writes (`reasonix config`, TUI settings,
      # migrations) warn and no-op, which reasonix tolerates.
      reasonixConfig = ''
        config_version = 5
        default_model = "deepseek-flash"
        language      = "zh"

        [ui]
        theme = "auto"
        show_reasoning = true

        [notifications]
        enabled          = true
        turn_done        = true
        approval_request = true
        ask_request      = true

        [telemetry]
        cli_metrics = "off"

        [desktop]
        telemetry = false
        metrics = false

        [agent]
        temperature = 0.0
        auto_plan   = "off"
        soft_compact_ratio  = 0.5
        compact_ratio       = 0.8
        compact_force_ratio = 0.9
        # planner_model  = "deepseek-pro"
        # subagent_model = "deepseek-pro"

        [[providers]]
        name        = "deepseek-flash"
        kind        = "openai"
        base_url    = "https://api.deepseek.com"
        models      = ["deepseek-v4-flash", "deepseek-v4-pro"]
        default     = "deepseek-v4-flash"   # optional; defaults to the first of `models`        
        api_key_env = "DEEPSEEK_API_KEY"
        balance_url = "https://api.deepseek.com/user/balance"
        effort      = "high"
        context_window = 1000000

        [tools]
        enabled = []
        bash_timeout_seconds = 120

        [serve]
        auth_mode = "none"                           # none|token|password
        behind_proxy = false                         # true only behind trusted proxy

        [permissions]
        mode = "ask"

        [sandbox]
        workspace_root = ""
        allow_write    = ["/tmp"]
        bash    = "enforce"
        network = true
      '';
    in
    {
      home.packages = [
        pkgs.llm-agents.codegraph
        reasonixWrapped
      ];

      # Declarative, read-only config (store symlink). force = true replaces
      # any previous copy or stale store link on re-activation.
      xdg.configFile."reasonix/config.toml".force = true;
      xdg.configFile."reasonix/config.toml".text = reasonixConfig;

      # The credential .env is seeded once from agenix and left alone
      # afterwards so keys added interactively are not clobbered.
      home.activation.setupReasonixEnv = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
        mkdir -p "${reasonixHome}"
        if [ ! -e "${reasonixHome}/.env" ] && [ -r "${deepseek-api-key.path}" ]; then
          umask 077
          printf 'DEEPSEEK_API_KEY=%s\n' "$(cat "${deepseek-api-key.path}")" > "${reasonixHome}/.env"
        fi
      '';

      age.secrets = {
        deepseek-api-key.file = ../../secrets/deepseek-api-key.age;
      };
    };
}
