theme = "adwaita-dark_transparent"

[editor]
auto-format = false
auto-save = true
bufferline = "multiple"
cursorcolumn = false
cursorline = true
idle-timeout = 100
line-number = "absolute"
mouse = true
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
character = "╎"
render = true
skip-levels = 0

[editor.lsp]
display-inlay-hints = true
display-messages = true
enable = true

[editor.soft-wrap]
enable = true
wrap-indicator = "↩ "

[editor.statusline]
center = []
left = ["mode", "file-name", "spinner"]
right = [
    "diagnostics",
    "selections",
    "position",
    "file-encoding",
    "file-line-ending",
    "file-type",
]
separator = "│"

[editor.statusline.mode]
insert = "I"
normal = "N"
select = "V"

[editor.whitespace.characters]
nbsp = "⍽"
newline = "⏎"
nnbsp = "␣"
space = "·"
tab = "→"
tabpad = "·"

[editor.whitespace.render]
nbsp = "all"
newline = "none"
nnbsp = "all"
space = "none"
tab = "all"

